# -*- coding: utf-8 -*-
"""COMP262_group7_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yNxWAG6L485zByF4wTaHnlEfNZbzVHBl
"""

!pip install vaderSentiment textblob transformers accelerate sentencepiece
import pandas as pd
import os

print("Current directory:", os.getcwd())

df = pd.read_json("Software_5.json", lines=True)

print("Shape (rows, cols):", df.shape)
print("\nColumns:\n", df.columns)
print("\nFirst 3 rows:\n", df.head(3))

print("\n--- BASIC STATS ---")
print("Total reviews:", len(df))
print("Unique users (reviewerID):", df["reviewerID"].nunique())
print("Unique products (asin):", df["asin"].nunique())

print("\n--- MISSING VALUES (top) ---")
print(df.isna().sum().sort_values(ascending=False).head(10))

print("\n--- DUPLICATES ---")
dup_subset = ["reviewerID", "asin", "reviewTime", "overall", "reviewText", "summary"]
print("Duplicate rows (subset):", df.duplicated(subset=dup_subset).sum())

print("\n--- RATINGS DISTRIBUTION (overall) ---")
print(df["overall"].value_counts().sort_index())

import matplotlib.pyplot as plt
rating_counts = df["overall"].value_counts().sort_index()

plt.figure(figsize=(6,4))
rating_counts.plot(kind="bar")
plt.title("Ratings Distribution (Software_5)")
plt.xlabel("Rating (overall)")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("ratings_distribution.png", dpi=200)
plt.show()

df["review_length"] = df["reviewText"].astype(str).apply(lambda x: len(x.split()))

print("\n--- REVIEW LENGTH STATS ---")
print("Average length:", df["review_length"].mean())
print("Min length:", df["review_length"].min())
print("Max length:", df["review_length"].max())

plt.figure(figsize=(6,4))
plt.hist(df["review_length"], bins=50)
plt.title("Review Length Distribution")
plt.xlabel("Number of Words")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("review_length_distribution.png", dpi=200)
plt.show()

def label_sentiment(rating):
    if rating >= 4:
        return "Positive"
    elif rating == 3:
        return "Neutral"
    else:
        return "Negative"

df["sentiment_label"] = df["overall"].apply(label_sentiment)

print("\n--- SENTIMENT LABEL DISTRIBUTION ---")
print(df["sentiment_label"].value_counts())

df["summary"] = df["summary"].fillna("")
df["reviewText"] = df["reviewText"].fillna("")

df["text"] = df["summary"] + " " + df["reviewText"]

print("\nExample combined text:\n")
print(df["text"].iloc[0][:300])

import re


def preprocess_text(text):
    text = text.lower()
    text = re.sub(r"\s+", " ", text)  # remove extra whitespace
    return text.strip()

df["clean_text"] = df["text"].apply(preprocess_text)

print("\nExample cleaned text:\n")
print(df["clean_text"].iloc[0][:300])

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

analyzer = SentimentIntensityAnalyzer()

def vader_predict(text):
    score = analyzer.polarity_scores(text)["compound"]

    if score >= 0.05:
        return "Positive"
    elif score <= -0.05:
        return "Negative"
    else:
        return "Neutral"

df["vader_prediction"] = df["clean_text"].apply(vader_predict)

print("\n--- VADER PREDICTION DISTRIBUTION ---")
print(df["vader_prediction"].value_counts())


from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
y_true = df["sentiment_label"]
y_pred = df["vader_prediction"]

print("\n--- VADER ACCURACY ---")
print("Accuracy:", accuracy_score(y_true, y_pred))

print("\n--- CLASSIFICATION REPORT ---")
print(classification_report(y_true, y_pred))

print("\n--- CONFUSION MATRIX ---")
print(confusion_matrix(y_true, y_pred))

from textblob import TextBlob

def textblob_predict(text):
    polarity = TextBlob(text).sentiment.polarity
    if polarity > 0:
        return "Positive"
    elif polarity < 0:
        return "Negative"
    else:
        return "Neutral"

df["textblob_prediction"] = df["clean_text"].apply(textblob_predict)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("TEXTBLOB FULL DATA ACCURACY:")
print(accuracy_score(df["sentiment_label"], df["textblob_prediction"]))

sample_df = df.sample(n=1000, random_state=42)

y_true_sample = sample_df["sentiment_label"]

y_vader_sample = sample_df["vader_prediction"]
y_textblob_sample = sample_df["textblob_prediction"]

print("\nVADER SAMPLE ACCURACY:")
print(accuracy_score(y_true_sample, y_vader_sample))

print("\nVADER SAMPLE CONFUSION MATRIX:")
print(confusion_matrix(y_true_sample, y_vader_sample))

print("\nTEXTBLOB SAMPLE ACCURACY:")
print(accuracy_score(y_true_sample, y_textblob_sample))

print("\nTEXTBLOB SAMPLE CONFUSION MATRIX:")
print(confusion_matrix(y_true_sample, y_textblob_sample))

print("\nVADER CLASSIFICATION REPORT:")
print(classification_report(y_true_sample, y_vader_sample))

print("\nTEXTBLOB CLASSIFICATION REPORT:")
print(classification_report(y_true_sample, y_textblob_sample))

!pip install vaderSentiment textblob transformers sentencepiece accelerate -q

import pandas as pd
import numpy as np
import re
import json
import warnings
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from textblob import TextBlob

from transformers import pipeline

warnings.filterwarnings("ignore")

DATA_FILE = "Software_5.json"
RANDOM_STATE = 42

print("Loading dataset...")
df = pd.read_json(DATA_FILE, lines=True)

print("Dataset shape:", df.shape)
print(df.columns)

df["summary"] = df["summary"].fillna("")
df["reviewText"] = df["reviewText"].fillna("")
df["text"] = (df["summary"] + " " + df["reviewText"]).str.strip()

def label_sentiment(r):
    if r >= 4:
        return "Positive"
    elif r == 3:
        return "Neutral"
    else:
        return "Negative"

df["sentiment_label"] = df["overall"].apply(label_sentiment)

def clean_text(t):
    t = str(t).lower()
    t = re.sub(r"http\S+|www\S+", " ", t)
    t = re.sub(r"<.*?>", " ", t)
    t = re.sub(r"[^a-zA-Z0-9\s']", " ", t)
    t = re.sub(r"\s+", " ", t)
    return t.strip()

df["clean_text"] = df["text"].apply(clean_text)
df["review_length"] = df["reviewText"].astype(str).apply(lambda x: len(x.split()))

print("\nPHASE 1 / GENERAL EXPLORATION")
print("Total reviews:", len(df))
print("Unique users:", df["reviewerID"].nunique())
print("Unique products:", df["asin"].nunique())
print("\nMissing values:")
print(df.isna().sum().sort_values(ascending=False).head(10))

dup_subset = ["reviewerID", "asin", "reviewTime", "overall", "reviewText", "summary"]
dup_subset = [c for c in dup_subset if c in df.columns]
print("\nDuplicate rows:", df.duplicated(subset=dup_subset).sum())

print("\nRatings distribution:")
print(df["overall"].value_counts().sort_index())

print("\nSentiment label distribution:")
print(df["sentiment_label"].value_counts())

print("\nReview length stats:")
print(df["review_length"].describe())

plt.figure(figsize=(6,4))
df["overall"].value_counts().sort_index().plot(kind="bar")
plt.title("Ratings Distribution (Software_5)")
plt.xlabel("Rating")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("ratings_distribution.png", dpi=200)
plt.show()

plt.figure(figsize=(6,4))
plt.hist(df["review_length"], bins=50)
plt.title("Review Length Distribution")
plt.xlabel("Number of Words")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("review_length_distribution.png", dpi=200)
plt.show()

print("\nPHASE 1 LEXICON SAMPLE")
phase1_sample = df.sample(n=1000, random_state=RANDOM_STATE).copy()

analyzer = SentimentIntensityAnalyzer()

def vader_predict(t):
    score = analyzer.polarity_scores(t)["compound"]
    if score >= 0.05:
        return "Positive"
    elif score <= -0.05:
        return "Negative"
    else:
        return "Neutral"

def textblob_predict(t):
    polarity = TextBlob(t).sentiment.polarity
    if polarity > 0:
        return "Positive"
    elif polarity < 0:
        return "Negative"
    else:
        return "Neutral"

phase1_sample["vader_prediction"] = phase1_sample["clean_text"].apply(vader_predict)
phase1_sample["textblob_prediction"] = phase1_sample["clean_text"].apply(textblob_predict)

print("\nVADER sample accuracy:", accuracy_score(phase1_sample["sentiment_label"], phase1_sample["vader_prediction"]))
print(confusion_matrix(phase1_sample["sentiment_label"], phase1_sample["vader_prediction"]))
print(classification_report(phase1_sample["sentiment_label"], phase1_sample["vader_prediction"], zero_division=0))

print("\nTextBlob sample accuracy:", accuracy_score(phase1_sample["sentiment_label"], phase1_sample["textblob_prediction"]))
print(confusion_matrix(phase1_sample["sentiment_label"], phase1_sample["textblob_prediction"]))
print(classification_report(phase1_sample["sentiment_label"], phase1_sample["textblob_prediction"], zero_division=0))

print("\nPHASE 2 MACHINE LEARNING")
subset = df.sample(n=3000, random_state=RANDOM_STATE).copy()

print("Subset size:", subset.shape)
print("\nSubset rating distribution:")
print(subset["overall"].value_counts().sort_index())
print("\nSubset sentiment distribution:")
print(subset["sentiment_label"].value_counts())

plt.figure(figsize=(6,4))
subset["overall"].value_counts().sort_index().plot(kind="bar")
plt.title("Phase 2 Subset Rating Distribution")
plt.xlabel("Rating")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("phase2_subset_rating_distribution.png", dpi=200)
plt.show()

plt.figure(figsize=(6,4))
plt.hist(subset["review_length"], bins=50)
plt.title("Phase 2 Subset Review Length Distribution")
plt.xlabel("Number of Words")
plt.ylabel("Count")
plt.tight_layout()
plt.savefig("phase2_subset_review_length_distribution.png", dpi=200)
plt.show()

X = subset["clean_text"]
y = subset["sentiment_label"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=RANDOM_STATE,
    stratify=subset["overall"]
)

print("Train size:", len(X_train))
print("Test size:", len(X_test))

vectorizer = TfidfVectorizer(stop_words="english", max_features=5000, ngram_range=(1,2))
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

print("\nTraining Logistic Regression...")
lr = LogisticRegression(max_iter=1000, class_weight="balanced")
lr.fit(X_train_tfidf, y_train)
lr_pred = lr.predict(X_test_tfidf)

print("\nLogistic Regression Results")
print("Accuracy:", accuracy_score(y_test, lr_pred))
print(confusion_matrix(y_test, lr_pred))
print(classification_report(y_test, lr_pred, zero_division=0))

print("\nTraining SVM...")
svm = LinearSVC(class_weight="balanced")
svm.fit(X_train_tfidf, y_train)
svm_pred = svm.predict(X_test_tfidf)

print("\nSVM Results")
print("Accuracy:", accuracy_score(y_test, svm_pred))
print(confusion_matrix(y_test, svm_pred))
print(classification_report(y_test, svm_pred, zero_division=0))

print("\nRunning lexicon models on the SAME Phase 2 test set...")
vader_pred = X_test.apply(vader_predict)
textblob_pred = X_test.apply(textblob_predict)

print("\nVADER Results")
print("Accuracy:", accuracy_score(y_test, vader_pred))
print(confusion_matrix(y_test, vader_pred))
print(classification_report(y_test, vader_pred, zero_division=0))

print("\nTextBlob Results")
print("Accuracy:", accuracy_score(y_test, textblob_pred))
print(confusion_matrix(y_test, textblob_pred))
print(classification_report(y_test, textblob_pred, zero_division=0))

def get_metrics(name, y_true, y_pred):
    report = classification_report(y_true, y_pred, output_dict=True, zero_division=0)
    return {
        "Model": name,
        "Accuracy": round(accuracy_score(y_true, y_pred), 4),
        "Macro_F1": round(f1_score(y_true, y_pred, average="macro"), 4),
        "Positive_Recall": round(report["Positive"]["recall"], 4),
        "Neutral_Recall": round(report["Neutral"]["recall"], 4),
        "Negative_Recall": round(report["Negative"]["recall"], 4)
    }

comparison_df = pd.DataFrame([
    get_metrics("Logistic Regression", y_test, lr_pred),
    get_metrics("SVM", y_test, svm_pred),
    get_metrics("VADER", y_test, vader_pred),
    get_metrics("TextBlob", y_test, textblob_pred)
])

print("\nFINAL MODEL COMPARISON")
print(comparison_df)

comparison_df.to_csv("phase2_model_comparison.csv", index=False)

comparison_df_plot = comparison_df.set_index("Model")[["Accuracy", "Macro_F1"]]
comparison_df_plot.plot(kind="bar", figsize=(8,5))
plt.title("Phase 2 Model Comparison")
plt.ylabel("Score")
plt.tight_layout()
plt.savefig("phase2_model_comparison.png", dpi=200)
plt.show()

print("\nPHASE 2 RECOMMENDER ENHANCEMENT")
subset["vader_compound"] = subset["clean_text"].apply(lambda x: analyzer.polarity_scores(x)["compound"])
subset["sentiment_score_1to5"] = ((subset["vader_compound"] + 1) / 2) * 4 + 1
subset["enhanced_rating"] = 0.7 * subset["overall"] + 0.3 * subset["sentiment_score_1to5"]

product_compare = subset.groupby("asin").agg(
    original_avg_rating=("overall", "mean"),
    enhanced_avg_rating=("enhanced_rating", "mean"),
    review_count=("overall", "count")
).reset_index()

product_compare = product_compare[product_compare["review_count"] >= 3].copy()
product_compare["original_rank"] = product_compare["original_avg_rating"].rank(method="dense", ascending=False)
product_compare["enhanced_rank"] = product_compare["enhanced_avg_rating"].rank(method="dense", ascending=False)
product_compare["rank_change"] = product_compare["original_rank"] - product_compare["enhanced_rank"]
product_compare = product_compare.sort_values(by="rank_change", ascending=False)

print("\nTop 10 products improved after sentiment-based enhancement:")
print(product_compare.head(10))

product_compare.to_csv("phase2_recommender_enhancement.csv", index=False)

top5_original = product_compare.sort_values("original_avg_rating", ascending=False).head(5)
top5_enhanced = product_compare.sort_values("enhanced_avg_rating", ascending=False).head(5)

print("\nTop 5 by original rating:")
print(top5_original[["asin", "original_avg_rating", "review_count"]])

print("\nTop 5 by enhanced rating:")
print(top5_enhanced[["asin", "enhanced_avg_rating", "review_count"]])

print("\nPHASE 2 LLM TASKS")
long_reviews = subset[subset["review_length"] > 100][["asin", "overall", "reviewText"]].head(10).copy()
question_reviews = subset[subset["reviewText"].str.contains(r"\?", regex=True, na=False)][["asin", "overall", "reviewText"]].head(1).copy()

long_reviews.to_csv("phase2_long_reviews_for_llm.csv", index=False)
question_reviews.to_csv("phase2_question_review_for_llm.csv", index=False)

print("\n10 long reviews selected for summarization.")
print(long_reviews.head(2))

print("\n1 question-style review selected for service response.")
print(question_reviews)

generator = pipeline("text-generation", model="distilgpt2")

summaries = []
for _, row in long_reviews.iterrows():
    text = str(row["reviewText"])[:500]
    prompt = f"Summarize this review in about 50 words:\n{text}\nSummary:"
    try:
        output = generator(prompt, max_new_tokens=80, num_return_sequences=1)[0]["generated_text"]
        summary = output.split("Summary:")[-1].strip()
    except:
        summary = "Summary generation failed for this review."
    summaries.append(summary)

long_reviews["summary_50_words"] = summaries
long_reviews.to_csv("phase2_long_reviews_with_summaries.csv", index=False)

print("\nFirst 2 summarized reviews:")
print(long_reviews[["reviewText", "summary_50_words"]].head(2))

if len(question_reviews) > 0:
    qtext = str(question_reviews.iloc[0]["reviewText"])[:500]
    prompt = f"Write a polite customer service response to this customer review:\n{qtext}\nResponse:"
    try:
        output = generator(prompt, max_new_tokens=120, num_return_sequences=1)[0]["generated_text"]
        response = output.split("Response:")[-1].strip()
    except:
        response = "Customer service response generation failed."
else:
    response = "No question-style review found."

print("\nGenerated customer service response:")
print(response)

with open("phase2_customer_service_response.txt", "w") as f:
    f.write(response)

all_outputs = {
    "phase2_subset_size": int(len(subset)),
    "train_size": int(len(X_train)),
    "test_size": int(len(X_test)),
    "comparison_results": comparison_df.to_dict(orient="records"),
    "top_10_improved_products": product_compare.head(10).to_dict(orient="records"),
    "first_2_summaries": long_reviews[["asin", "summary_50_words"]].head(2).to_dict(orient="records"),
    "customer_service_response": response
}

with open("phase2_outputs.json", "w") as f:
    json.dump(all_outputs, f, indent=4)

print("\nDONE. Files saved:")
print("- phase2_model_comparison.csv")
print("- phase2_model_comparison.png")
print("- phase2_recommender_enhancement.csv")
print("- phase2_long_reviews_for_llm.csv")
print("- phase2_long_reviews_with_summaries.csv")
print("- phase2_question_review_for_llm.csv")
print("- phase2_customer_service_response.txt")
print("- phase2_outputs.json")